project:
  type: website
  output-dir: docs

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home Tab"
        file: index.qmd
      - text: "MLuno Reference"
        file: reference/index.qmd
quartodoc:
  # the name used to import the package you want to create reference docs for
  package: mluno
  sidebar: _sidebar.yml
  sections:
    - title: Data Utilities
      desc: Functions to simulate and split data
      package: mluno.data
      contents:
        - make_line_data
        - make_sine_data
        - split_data
    - title: Regressors
      desc: Linear and KNN regressors class functions
      package: mluno.regressors
      contents:
        - KNNRegressor
        - LinearRegressor
    - title: Conformal Prediction
      desc: A class used to represent a Conformal Predictor.
      package: mluno.conformal
      contents:
        - ConformalPredictor      
    - title: Metrics
      desc: Metrics
      package: mluno.metrics
      contents:
        - rmse
        - mae
        - coverage
        - sharpness
    - title: Plotting
      desc: Plotting
      package: mluno.plot
      contents:
        - plot_predictions